#This Docker-compose is what ties all the containers together. 
#This makes for brining up DMS Service easier
version: "3.3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./dms-lite
    ports:
      - "3000:3000"
    volumes:
      - "~/CLionProjects/dms-lite-docker:/db:z"
  serialwriter:
      depends_on:
        - "web"
      build:
        dockerfile: Dockerfile
        context: ./serial-sql-writer
      volumes:
        - "~/CLionProjects/dms-lite-docker:/db:z"
        - "/dev/ttyUSB0:/dev/ttyUSB0:z"
      privileged: true 
