#This Docker-compose is what ties all the containers together. 
#This makes for brining up DMS Service easier
version: "3.3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./dms-lite
    ports:
      - "3000:3000"
    volumes:
      - "~/CLionProjects/dms-lite-docker:/db:z"
    user: "1000:1000"

  MQTT-Server:
      container_name: mqtt_broker
      hostname: mosquitto
      image: eclipse-mosquitto:latest
      ports: 
        - "1883:1883"
      volumes:
         - "./mosquitto.conf:/mosquitto/config/mosquitto.conf:z"
      user: "1000:1000"

  wifiwriter:
      depends_on:
        - "MQTT-Server"
      build:
        dockerfile: Dockerfile
        context: ./Wifi-sql-writer
      volumes:
        - "~/CLionProjects/dms-lite-docker:/db:z"
      user: "1000:1000"
